- name: Download Linkerd CLI
  get_url:
    url: "{{ linkerd_cli_url }}"
    dest: /tmp/linkerd-cli
    mode: '0755'

- name: Move Linkerd CLI to system path
  copy:
    src: /tmp/linkerd-cli
    dest: "{{ linkerd_cli_path }}"
    remote_src: yes
    mode: '0755'

- name: Verify Linkerd CLI installation
  command: "{{ linkerd_cli_path }} version --client"
  register: linkerd_version_check
  changed_when: false
  failed_when: "'Client version' not in linkerd_version_check.stdout"

- name: Check Kubernetes cluster compatibility
  command: "{{ linkerd_cli_path }} check --pre"
  register: linkerd_pre_check
  changed_when: false
  failed_when: "'Linkerd is checking the following' not in linkerd_pre_check.stdout"

- name: Install Linkerd control plane
  command: "{{ linkerd_cli_path }} install | kubectl apply -f -"
  register: linkerd_install
  changed_when: "'Linkerd control plane' in linkerd_install.stdout"

- name: Verify Linkerd installation
  command: "{{ linkerd_cli_path }} check"
  register: linkerd_check
  changed_when: false
  failed_when: "'Linkerd is running' not in linkerd_check.stdout"

- name: Enable automatic sidecar injection for default namespace
  command: "kubectl annotate namespace default linkerd.io/inject=enabled --overwrite"
  changed_when: true
