apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    linkerd.io/control-plane-ns: linkerd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-controller
  namespace: linkerd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-identity
  namespace: linkerd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-identity
  namespace: linkerd
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 9999
      name: admin
      targetPort: 9999
  selector:
    linkerd.io/control-plane-component: identity
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    linkerd.io/control-plane-component: proxy-injector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: linkerd
data:
  identity-trust-anchors.pem: |
    -----BEGIN CERTIFICATE-----
    # Add your CA certificate here
    -----END CERTIFICATE-----
  proxy-log-level: info
  linkerd-version: stable-2.13.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-identity
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: identity
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: identity
    spec:
      serviceAccountName: linkerd-identity
      containers:
        - name: identity
          image: ghcr.io/linkerd/identity:stable-2.13.2
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9999
              name: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: proxy-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: proxy-injector
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: proxy-injector
    spec:
      serviceAccountName: linkerd-proxy-injector
      containers:
        - name: proxy-injector
          image: ghcr.io/linkerd/proxy-injector:stable-2.13.2
          ports:
            - containerPort: 8443
              name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: controller
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: controller
    spec:
      serviceAccountName: linkerd-controller
      containers:
        - name: controller
          image: ghcr.io/linkerd/controller:stable-2.13.2
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9999
              name: admin
