apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-webui
  template:
    metadata:
      labels:
        app: teastore-webui
    spec:
      containers:
        - name: webui
          image: descartesresearch/teastore-webui:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore-persistence
    spec:
      containers:
        - name: persistence
          image: descartesresearch/teastore-persistence:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore-recommender
    spec:
      containers:
        - name: recommender
          image: descartesresearch/teastore-recommender:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-auth
  template:
    metadata:
      labels:
        app: teastore-auth
    spec:
      containers:
        - name: auth
          image: descartesresearch/teastore-auth:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-registry
  template:
    metadata:
      labels:
        app: teastore-registry
    spec:
      containers:
        - name: registry
          image: descartesresearch/teastore-registry:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  namespace: teastore
spec:
  selector:
    app: teastore-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  namespace: teastore
spec:
  selector:
    app: teastore-persistence
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-recommender
  namespace: teastore
spec:
  selector:
    app: teastore-recommender
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  namespace: teastore
spec:
  selector:
    app: teastore-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  namespace: teastore
spec:
  selector:
    app: teastore-registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
