- name: Update apt packages
  apt:
    update_cache: yes

- name: Install basic tools
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
      - python3-pip
    state: present
