# apiVersion: v1
# kind: Pod
# metadata:
#   name: fortio-client
#   namespace: default
#   labels:
#     app: fortio-client
#   annotations:
#     sidecar.istio.io/inject: "false"
# spec:
#   containers:
#     - name: fortio
#       image: fortio/fortio:latest
#       command: ["/usr/bin/fortio", "server"]
#       ports:
#         - containerPort: 8080
#       resources:
#         limits:
#           cpu: 250m
#           memory: 256Mi
#         requests:
#           cpu: 100m
#           memory: 128Mi
#   restartPolicy: Never

apiVersion: v1
kind: Pod
metadata:
  name: fortio-client
  namespace: default
  labels:
    app: fortio-client
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: fortio
      image: ubuntu:22.04
      command: ["/bin/bash", "-c"]
      args:
        - |
          apt update && \
          apt install -y curl wget gnupg ca-certificates && \
          wget https://github.com/fortio/fortio/releases/download/v1.69.1/fortio-linux_amd64-1.69.1.tgz && \
          tar -xzf fortio-linux_amd64-1.69.1.tgz && \
          cp usr/bin/fortio /usr/local/bin/ && \
          chmod +x /usr/local/bin/fortio && \
          echo "Fortio is ready!" && \
          tail -f /dev/null
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
  restartPolicy: Never
