apiVersion: v1
kind: Service
metadata:
  name: traefik-mesh-proxy
  namespace: traefik-mesh
  labels:
    app.kubernetes.io/name: traefik-mesh-proxy
spec:
  selector:
    app: maesh
    component: maesh-mesh
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: metrics
      port: 8080
      targetPort: 8080
