apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'custom-dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/custom-dashboards


# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-dashboard
#   namespace: monitoring
# data:
#   node-exporter-dashboard.json: |
#     {
#       "annotations": {
#         "list": []
#       },
#       "title": "Node Exporter Full",
#       "uid": "node-exporter",
#       "version": 1,
#       "schemaVersion": 22,
#       "panels": [
#         {
#           "title": "CPU Usage",
#           "type": "graph",
#           "targets": [
#             {
#               "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)",
#               "legendFormat": "{{instance}}",
#               "refId": "A"
#             }
#           ]
#         }
#       ]
#     }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "P3dL9vJXfTgqZ2Nm"
            - name: GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE
              value: "true"
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
          volumeMounts:
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/custom-dashboards
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
