{
 "title": "Monitoring dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_network_transmit_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}