apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: allow-caller-hello
  namespace: default
spec:
  destination:
    name: hello
  sources:
    - name: caller
      action: allow
