apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller
  template:
    metadata:
      labels:
        app: caller
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
        - name: curl
          image: curlimages/curl:7.85.0
          command: ["sleep", "3600"]

---
apiVersion: v1
kind: Service
metadata:
  name: caller
  namespace: default
spec:
  selector:
    app: caller
  ports:
    - port: 80
      targetPort: 80
