apiVersion: v1
kind: Pod
metadata:
  name: grpc-caller
  annotations:
    consul.hashicorp.com/connect-inject: "false"
spec:
  containers:
    - name: grpcurl
      image: fullstorydev/grpcurl
      args: ["-plaintext", "hello-grpc:50051", "list"]
