apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-grpc-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-grpc-2
  template:
    metadata:
      labels:
        app: hello-grpc-2
    spec:
      containers:
        - name: server
          image: jbrandhorst/grpc-hello-world-server
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: hello-grpc-2
spec:
  selector:
    app: hello-grpc-2
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
