istio_version: "1.18.0"
istio_profile: "default"
download_url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux-amd64.tar.gz"
istio_home: "/usr/local/istio-{{ istio_version }}"
